name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code test
        uses: actions/checkout@v2

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Exécuter les tests
        run: pytest test_api.py

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Construire l'image Docker
        run: docker build -t filmpy .

      - name: Authentification à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tagger l'image Docker
        run: docker tag filmpy d0coeur/filmpy:latest

      - name: Pousser l'image Docker sur Docker Hub
        run: docker push d0coeur/filmpy:latest
